-- LinkAlive clean baseline for MySQL 8.x and MariaDB 11.x.
-- UUID values are generated by Prisma (or UUID() in the few raw-SQL writers),
-- and every DATETIME(3) value is UTC by application contract.
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `monitors` (
    `id` CHAR(36) NOT NULL,
    `name` VARCHAR(160) NOT NULL,
    `request_url_encrypted` BLOB NOT NULL,
    `display_url` VARCHAR(2048) NOT NULL,
    `hostname_normalized` VARCHAR(253) NOT NULL,
    `method` ENUM('GET', 'HEAD') NOT NULL DEFAULT 'GET',
    `interval_sec` INTEGER NOT NULL DEFAULT 60,
    `timeout_ms` INTEGER NOT NULL DEFAULT 10000,
    `expected_status_min` SMALLINT NOT NULL DEFAULT 200,
    `expected_status_max` SMALLINT NOT NULL DEFAULT 299,
    `expected_keyword` VARCHAR(512) NULL,
    `follow_redirects` BOOLEAN NOT NULL DEFAULT true,
    `max_redirects` SMALLINT NOT NULL DEFAULT 5,
    `failure_threshold` SMALLINT NOT NULL DEFAULT 3,
    `recovery_threshold` SMALLINT NOT NULL DEFAULT 2,
    `lifecycle_status` ENUM('ACTIVE', 'PAUSED', 'DELETED') NOT NULL DEFAULT 'ACTIVE',
    `health_state` ENUM('PENDING', 'UP', 'SUSPECT', 'DOWN', 'RECOVERING') NOT NULL DEFAULT 'PENDING',
    `consecutive_failures` INTEGER NOT NULL DEFAULT 0,
    `consecutive_successes` INTEGER NOT NULL DEFAULT 0,
    `failure_streak_started_at` DATETIME(3) NULL,
    `failure_streak_first_error_type` ENUM('DNS_ERROR', 'CONNECT_TIMEOUT', 'CONNECTION_REFUSED', 'TLS_ERROR', 'TTFB_TIMEOUT', 'REQUEST_TIMEOUT', 'REDIRECT_ERROR', 'HTTP_STATUS_MISMATCH', 'CONTENT_MISMATCH', 'RESPONSE_LIMIT_EXCEEDED', 'NETWORK_ERROR', 'PLATFORM_ERROR') NULL,
    `last_checked_at` DATETIME(3) NULL,
    `last_success_at` DATETIME(3) NULL,
    `last_failure_at` DATETIME(3) NULL,
    `last_status_code` SMALLINT NULL,
    `last_ttfb_ms` INTEGER NULL,
    `last_total_ms` INTEGER NULL,
    `last_error_type` ENUM('DNS_ERROR', 'CONNECT_TIMEOUT', 'CONNECTION_REFUSED', 'TLS_ERROR', 'TTFB_TIMEOUT', 'REQUEST_TIMEOUT', 'REDIRECT_ERROR', 'HTTP_STATUS_MISMATCH', 'CONTENT_MISMATCH', 'RESPONSE_LIMIT_EXCEEDED', 'NETWORK_ERROR', 'PLATFORM_ERROR') NULL,
    `next_check_at` DATETIME(3) NULL,
    `config_version` INTEGER NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `deleted_at` DATETIME(3) NULL,

    INDEX `monitors_due_idx`(`lifecycle_status`, `next_check_at`),
    INDEX `monitors_health_idx`(`health_state`),
    INDEX `monitors_hostname_idx`(`hostname_normalized`),
    INDEX `monitors_deleted_at_idx`(`deleted_at`),
    PRIMARY KEY (`id`),
    CONSTRAINT `monitors_required_text_check` CHECK (
      CHAR_LENGTH(TRIM(`name`)) > 0
      AND OCTET_LENGTH(`request_url_encrypted`) > 0
      AND CHAR_LENGTH(TRIM(`display_url`)) > 0
      AND CHAR_LENGTH(TRIM(`hostname_normalized`)) > 0
    ),
    CONSTRAINT `monitors_interval_check` CHECK (`interval_sec` IN (60, 300, 600, 1800, 3600)),
    CONSTRAINT `monitors_timeout_check` CHECK (`timeout_ms` BETWEEN 1000 AND 30000),
    CONSTRAINT `monitors_expected_status_check` CHECK (
      `expected_status_min` BETWEEN 100 AND 599
      AND `expected_status_max` BETWEEN 100 AND 599
      AND `expected_status_min` <= `expected_status_max`
    ),
    CONSTRAINT `monitors_keyword_method_check` CHECK (`method` <> 'HEAD' OR `expected_keyword` IS NULL),
    CONSTRAINT `monitors_thresholds_check` CHECK (
      `max_redirects` BETWEEN 0 AND 5
      AND `failure_threshold` BETWEEN 1 AND 10
      AND `recovery_threshold` BETWEEN 1 AND 10
    ),
    CONSTRAINT `monitors_state_counts_check` CHECK (
      `consecutive_failures` >= 0 AND `consecutive_successes` >= 0 AND `config_version` >= 1
    ),
    CONSTRAINT `monitors_last_measurements_check` CHECK (
      (`last_status_code` IS NULL OR `last_status_code` BETWEEN 100 AND 999)
      AND (`last_ttfb_ms` IS NULL OR `last_ttfb_ms` >= 0)
      AND (`last_total_ms` IS NULL OR `last_total_ms` >= 0)
    ),
    CONSTRAINT `monitors_deleted_lifecycle_check` CHECK (
      (`lifecycle_status` = 'DELETED' AND `deleted_at` IS NOT NULL)
      OR (`lifecycle_status` <> 'DELETED' AND `deleted_at` IS NULL)
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `scheduled_checks` (
    `id` CHAR(36) NOT NULL,
    `monitor_id` CHAR(36) NOT NULL,
    `scheduled_at` DATETIME(3) NOT NULL,
    `config_version` INTEGER NOT NULL,
    `status` ENUM('PENDING', 'ENQUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELED') NOT NULL DEFAULT 'PENDING',
    `lease_owner` VARCHAR(160) NULL,
    `lease_until` DATETIME(3) NULL,
    `queue_job_id` VARCHAR(160) NULL,
    `attempt_count` INTEGER NOT NULL DEFAULT 0,
    `failure_reason_safe` VARCHAR(1024) NULL,
    `enqueued_at` DATETIME(3) NULL,
    `started_at` DATETIME(3) NULL,
    `completed_at` DATETIME(3) NULL,
    `canceled_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `active_monitor_id` VARCHAR(36)
      GENERATED ALWAYS AS (
        CASE
          WHEN `status` IN ('PENDING', 'ENQUEUED', 'RUNNING') THEN RTRIM(`monitor_id`)
          ELSE NULL
        END
      ) STORED,

    INDEX `scheduled_checks_reconcile_idx`(`status`, `lease_until`),
    INDEX `scheduled_checks_monitor_created_idx`(`monitor_id`, `created_at` DESC),
    UNIQUE INDEX `scheduled_checks_schedule_key`(`monitor_id`, `scheduled_at`, `config_version`),
    UNIQUE INDEX `scheduled_checks_result_identity_key`(`id`, `monitor_id`, `config_version`),
    UNIQUE INDEX `scheduled_checks_one_active_per_monitor_idx`(`active_monitor_id`),
    INDEX `scheduled_checks_retention_terminal_idx`(`status`, `completed_at`, `canceled_at`, `updated_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `scheduled_checks_config_version_check` CHECK (`config_version` >= 1),
    CONSTRAINT `scheduled_checks_attempt_count_check` CHECK (`attempt_count` >= 0),
    CONSTRAINT `scheduled_checks_lease_pair_check` CHECK (
      (`lease_owner` IS NULL AND `lease_until` IS NULL)
      OR (`lease_owner` IS NOT NULL AND `lease_until` IS NOT NULL)
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `check_results` (
    `id` CHAR(36) NOT NULL,
    `monitor_id` CHAR(36) NULL,
    `scheduled_check_id` CHAR(36) NULL,
    `source` ENUM('SCHEDULED', 'MANUAL', 'TEST') NOT NULL,
    `outcome` ENUM('SUCCESS', 'TARGET_FAILURE', 'PLATFORM_ERROR', 'INCONCLUSIVE') NOT NULL,
    `config_version` INTEGER NULL,
    `display_url_snapshot` VARCHAR(2048) NOT NULL,
    `started_at` DATETIME(3) NOT NULL,
    `finished_at` DATETIME(3) NOT NULL,
    `status_code` SMALLINT NULL,
    `ttfb_ms` INTEGER NULL,
    `total_ms` INTEGER NOT NULL,
    `error_type` ENUM('DNS_ERROR', 'CONNECT_TIMEOUT', 'CONNECTION_REFUSED', 'TLS_ERROR', 'TTFB_TIMEOUT', 'REQUEST_TIMEOUT', 'REDIRECT_ERROR', 'HTTP_STATUS_MISMATCH', 'CONTENT_MISMATCH', 'RESPONSE_LIMIT_EXCEEDED', 'NETWORK_ERROR', 'PLATFORM_ERROR') NULL,
    `error_message_safe` VARCHAR(1024) NULL,
    `worker_region` VARCHAR(80) NULL,
    `redirect_count` SMALLINT NOT NULL DEFAULT 0,
    `response_bytes_read` INTEGER NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `check_results_monitor_started_idx`(`monitor_id`, `started_at` DESC),
    INDEX `check_results_outcome_started_idx`(`outcome`, `started_at`),
    INDEX `check_results_retention_idx`(`created_at`),
    UNIQUE INDEX `check_results_scheduled_identity_key`(`scheduled_check_id`, `monitor_id`, `config_version`),
    INDEX `check_results_retention_finished_idx`(`finished_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `check_results_source_ledger_check` CHECK (
      (
        `source` = 'SCHEDULED' AND `monitor_id` IS NOT NULL
        AND `scheduled_check_id` IS NOT NULL AND `config_version` IS NOT NULL
      )
      OR (
        `source` = 'MANUAL' AND `monitor_id` IS NOT NULL
        AND `scheduled_check_id` IS NULL AND `config_version` IS NOT NULL
      )
      OR (
        `source` = 'TEST' AND `monitor_id` IS NULL
        AND `scheduled_check_id` IS NULL AND `config_version` IS NULL
      )
    ),
    CONSTRAINT `check_results_display_snapshot_check` CHECK (CHAR_LENGTH(TRIM(`display_url_snapshot`)) > 0),
    CONSTRAINT `check_results_timing_check` CHECK (
      `finished_at` >= `started_at` AND `total_ms` >= 0
      AND (`ttfb_ms` IS NULL OR `ttfb_ms` >= 0)
    ),
    CONSTRAINT `check_results_status_code_check` CHECK (`status_code` IS NULL OR `status_code` BETWEEN 100 AND 999),
    CONSTRAINT `check_results_counts_check` CHECK (
      `redirect_count` BETWEEN 0 AND 5
      AND (`response_bytes_read` IS NULL OR `response_bytes_read` >= 0)
    ),
    CONSTRAINT `check_results_config_version_check` CHECK (`config_version` IS NULL OR `config_version` >= 1),
    CONSTRAINT `check_results_success_error_check` CHECK (`outcome` <> 'SUCCESS' OR `error_type` IS NULL),
    CONSTRAINT `check_results_target_error_check` CHECK (
      `outcome` <> 'TARGET_FAILURE'
      OR (`error_type` IS NOT NULL AND `error_type` <> 'PLATFORM_ERROR')
    ),
    CONSTRAINT `check_results_platform_error_check` CHECK (
      `outcome` <> 'PLATFORM_ERROR' OR `error_type` = 'PLATFORM_ERROR'
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `incidents` (
    `id` CHAR(36) NOT NULL,
    `monitor_id` CHAR(36) NOT NULL,
    `config_version` INTEGER NOT NULL,
    `status` ENUM('OPEN', 'RESOLVED', 'CANCELED') NOT NULL DEFAULT 'OPEN',
    `first_failure_at` DATETIME(3) NOT NULL,
    `detected_at` DATETIME(3) NOT NULL,
    `resolved_at` DATETIME(3) NULL,
    `canceled_at` DATETIME(3) NULL,
    `first_error_type` ENUM('DNS_ERROR', 'CONNECT_TIMEOUT', 'CONNECTION_REFUSED', 'TLS_ERROR', 'TTFB_TIMEOUT', 'REQUEST_TIMEOUT', 'REDIRECT_ERROR', 'HTTP_STATUS_MISMATCH', 'CONTENT_MISMATCH', 'RESPONSE_LIMIT_EXCEEDED', 'NETWORK_ERROR', 'PLATFORM_ERROR') NULL,
    `last_error_type` ENUM('DNS_ERROR', 'CONNECT_TIMEOUT', 'CONNECTION_REFUSED', 'TLS_ERROR', 'TTFB_TIMEOUT', 'REQUEST_TIMEOUT', 'REDIRECT_ERROR', 'HTTP_STATUS_MISMATCH', 'CONTENT_MISMATCH', 'RESPONSE_LIMIT_EXCEEDED', 'NETWORK_ERROR', 'PLATFORM_ERROR') NULL,
    `closure_reason` ENUM('RECOVERED', 'PAUSED', 'DELETED', 'CONFIG_CHANGED') NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `open_monitor_id` VARCHAR(36)
      GENERATED ALWAYS AS (
        CASE WHEN `status` = 'OPEN' THEN RTRIM(`monitor_id`) ELSE NULL END
      ) STORED,

    INDEX `incidents_monitor_detected_idx`(`monitor_id`, `detected_at` DESC),
    INDEX `incidents_status_detected_idx`(`status`, `detected_at` DESC),
    UNIQUE INDEX `incidents_one_open_per_monitor_idx`(`open_monitor_id`),
    INDEX `incidents_retention_closed_idx`(`status`, `resolved_at`, `canceled_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `incidents_config_version_check` CHECK (`config_version` >= 1),
    CONSTRAINT `incidents_detection_order_check` CHECK (`first_failure_at` <= `detected_at`),
    CONSTRAINT `incidents_closure_check` CHECK (
      (`status` = 'OPEN' AND `resolved_at` IS NULL AND `canceled_at` IS NULL AND `closure_reason` IS NULL)
      OR (
        `status` = 'RESOLVED' AND `resolved_at` IS NOT NULL
        AND `resolved_at` >= `detected_at` AND `canceled_at` IS NULL
        AND `closure_reason` = 'RECOVERED'
      )
      OR (
        `status` = 'CANCELED' AND `canceled_at` IS NOT NULL
        AND `canceled_at` >= `detected_at` AND `resolved_at` IS NULL
        AND `closure_reason` IN ('PAUSED', 'DELETED', 'CONFIG_CHANGED')
      )
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `notification_channels` (
    `id` CHAR(36) NOT NULL,
    `type` ENUM('EMAIL', 'TELEGRAM') NOT NULL,
    `display_name` VARCHAR(160) NOT NULL,
    `encrypted_config` BLOB NOT NULL,
    `verified_at` DATETIME(3) NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,
    `deleted_at` DATETIME(3) NULL,

    INDEX `notification_channels_active_idx`(`enabled`, `deleted_at`),
    PRIMARY KEY (`id`),
    CONSTRAINT `notification_channels_required_check` CHECK (
      CHAR_LENGTH(TRIM(`display_name`)) > 0 AND OCTET_LENGTH(`encrypted_config`) > 0
    ),
    CONSTRAINT `notification_channels_deleted_check` CHECK (`deleted_at` IS NULL OR `enabled` = FALSE)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `monitor_channels` (
    `monitor_id` CHAR(36) NOT NULL,
    `channel_id` CHAR(36) NOT NULL,
    `notify_on_down` BOOLEAN NOT NULL DEFAULT true,
    `notify_on_recovery` BOOLEAN NOT NULL DEFAULT true,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    INDEX `monitor_channels_channel_idx`(`channel_id`),
    PRIMARY KEY (`monitor_id`, `channel_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `notification_outbox` (
    `id` CHAR(36) NOT NULL,
    `monitor_id` CHAR(36) NOT NULL,
    `incident_id` CHAR(36) NULL,
    `channel_id` CHAR(36) NOT NULL,
    `event_type` ENUM('DOWN', 'RECOVERY', 'RESOLVED_SUMMARY', 'TEST') NOT NULL,
    `sequence` INTEGER NOT NULL,
    `dedupe_key` VARCHAR(512) NOT NULL,
    `payload_safe` JSON NOT NULL,
    `channel_type_snapshot` ENUM('EMAIL', 'TELEGRAM') NOT NULL,
    `channel_display_name_snapshot` VARCHAR(160) NOT NULL,
    `encrypted_config_snapshot` BLOB NOT NULL,
    `status` ENUM('PENDING', 'ENQUEUED', 'PROCESSING', 'RETRY', 'SENT', 'FAILED', 'CANCELED') NOT NULL DEFAULT 'PENDING',
    `available_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lease_owner` VARCHAR(160) NULL,
    `lease_until` DATETIME(3) NULL,
    `queue_job_id` VARCHAR(160) NULL,
    `message_id` VARCHAR(512) NOT NULL,
    `attempt_count` INTEGER NOT NULL DEFAULT 0,
    `max_attempts` SMALLINT NOT NULL DEFAULT 3,
    `last_error_safe` VARCHAR(1024) NULL,
    `enqueued_at` DATETIME(3) NULL,
    `processing_at` DATETIME(3) NULL,
    `sent_at` DATETIME(3) NULL,
    `failed_at` DATETIME(3) NULL,
    `canceled_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL,

    UNIQUE INDEX `notification_outbox_dedupe_key`(`dedupe_key`),
    INDEX `notification_outbox_dispatch_idx`(`status`, `available_at`),
    INDEX `notification_outbox_reconcile_idx`(`status`, `lease_until`),
    UNIQUE INDEX `notification_outbox_incident_channel_sequence_key`(`incident_id`, `channel_id`, `sequence`),
    INDEX `notification_outbox_retention_terminal_idx`(`status`, `sent_at`, `failed_at`, `canceled_at`, `updated_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `notification_outbox_sequence_check` CHECK (
      (`event_type` IN ('DOWN', 'TEST') AND `sequence` = 1)
      OR (`event_type` IN ('RECOVERY', 'RESOLVED_SUMMARY') AND `sequence` = 2)
    ),
    CONSTRAINT `notification_outbox_incident_check` CHECK (
      (`event_type` = 'TEST' AND `incident_id` IS NULL)
      OR (`event_type` <> 'TEST' AND `incident_id` IS NOT NULL)
    ),
    CONSTRAINT `notification_outbox_attempts_check` CHECK (
      `attempt_count` >= 0 AND `max_attempts` BETWEEN 1 AND 10 AND `attempt_count` <= `max_attempts`
    ),
    CONSTRAINT `notification_outbox_lease_pair_check` CHECK (
      (`lease_owner` IS NULL AND `lease_until` IS NULL)
      OR (`lease_owner` IS NOT NULL AND `lease_until` IS NOT NULL)
    ),
    CONSTRAINT `notification_outbox_required_check` CHECK (
      CHAR_LENGTH(TRIM(`message_id`)) > 0 AND OCTET_LENGTH(`encrypted_config_snapshot`) > 0
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `notification_deliveries` (
    `id` CHAR(36) NOT NULL,
    `outbox_id` CHAR(36) NOT NULL,
    `attempt` INTEGER NOT NULL,
    `status` ENUM('ATTEMPTING', 'SUCCEEDED', 'FAILED', 'UNKNOWN') NOT NULL DEFAULT 'ATTEMPTING',
    `message_id` VARCHAR(512) NOT NULL,
    `provider_message_id` VARCHAR(512) NULL,
    `error_safe` VARCHAR(1024) NULL,
    `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `finished_at` DATETIME(3) NULL,
    `sent_at` DATETIME(3) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `notification_deliveries_status_created_idx`(`status`, `created_at`),
    UNIQUE INDEX `notification_deliveries_attempt_key`(`outbox_id`, `attempt`),
    INDEX `notification_deliveries_retention_finished_idx`(`finished_at`, `created_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `notification_deliveries_attempt_check` CHECK (`attempt` >= 1),
    CONSTRAINT `notification_deliveries_time_check` CHECK (
      (`finished_at` IS NULL OR `finished_at` >= `started_at`)
      AND (`sent_at` IS NULL OR `sent_at` >= `started_at`)
    ),
    CONSTRAINT `notification_deliveries_message_id_check` CHECK (CHAR_LENGTH(TRIM(`message_id`)) > 0)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `audit_logs` (
    `id` CHAR(36) NOT NULL,
    `actor_id` VARCHAR(255) NULL,
    `action` VARCHAR(120) NOT NULL,
    `target_type` VARCHAR(80) NOT NULL,
    `target_id` VARCHAR(255) NOT NULL,
    `metadata_safe` JSON NULL,
    `request_id` VARCHAR(160) NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `audit_logs_target_created_idx`(`target_type`, `target_id`, `created_at` DESC),
    INDEX `audit_logs_actor_created_idx`(`actor_id`, `created_at` DESC),
    INDEX `audit_logs_created_idx`(`created_at`),
    INDEX `audit_logs_retention_batch_idx`(`created_at`, `id`),
    PRIMARY KEY (`id`),
    CONSTRAINT `audit_logs_action_check` CHECK (CHAR_LENGTH(TRIM(`action`)) > 0),
    CONSTRAINT `audit_logs_target_check` CHECK (
      CHAR_LENGTH(TRIM(`target_type`)) > 0 AND CHAR_LENGTH(TRIM(`target_id`)) > 0
    )
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `scheduled_checks` ADD CONSTRAINT `scheduled_checks_monitor_id_fkey` FOREIGN KEY (`monitor_id`) REFERENCES `monitors`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `check_results` ADD CONSTRAINT `check_results_monitor_id_fkey` FOREIGN KEY (`monitor_id`) REFERENCES `monitors`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `check_results` ADD CONSTRAINT `check_results_scheduled_identity_fkey` FOREIGN KEY (`scheduled_check_id`, `monitor_id`, `config_version`) REFERENCES `scheduled_checks`(`id`, `monitor_id`, `config_version`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `incidents` ADD CONSTRAINT `incidents_monitor_id_fkey` FOREIGN KEY (`monitor_id`) REFERENCES `monitors`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `monitor_channels` ADD CONSTRAINT `monitor_channels_monitor_id_fkey` FOREIGN KEY (`monitor_id`) REFERENCES `monitors`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `monitor_channels` ADD CONSTRAINT `monitor_channels_channel_id_fkey` FOREIGN KEY (`channel_id`) REFERENCES `notification_channels`(`id`) ON DELETE CASCADE ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notification_outbox` ADD CONSTRAINT `notification_outbox_monitor_id_fkey` FOREIGN KEY (`monitor_id`) REFERENCES `monitors`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notification_outbox` ADD CONSTRAINT `notification_outbox_incident_id_fkey` FOREIGN KEY (`incident_id`) REFERENCES `incidents`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notification_outbox` ADD CONSTRAINT `notification_outbox_channel_id_fkey` FOREIGN KEY (`channel_id`) REFERENCES `notification_channels`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE `notification_deliveries` ADD CONSTRAINT `notification_deliveries_outbox_id_fkey` FOREIGN KEY (`outbox_id`) REFERENCES `notification_outbox`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;
